server:
  port: 8090
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/egg_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

  jackson:
    serialization:
      write-dates-as-timestamps: false

  cache:
    type: redis
    cache-names: userCache

  redis:
    host: 127.0.0.1
    port: 6379
    password: ""
    timeout: 30000ms
    lettuce:
      pool:
        max-active: 32
        max-idle: 16
        min-idle: 8
        max-wait: 5000ms

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.egg.springboot_egg.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.egg.springboot_egg: INFO

springfox:
  documentation:
    swagger:
      v2:
        path: /v2/api-docs